### ISSUE TITLE
Hippo Web wallet issue

### ISSUE THREAD

**Issue by flappys** [hippospace/hippo-frontend#7]
Hippo web wallet opens in the same container as the web wallets and there is no option to close it. Page needs to be refreshed to close the hippo wallet. May be add one close icon.

**Comment by Manahip** [comment]
Things are moving so fast we don't have time to maintain our wallets anymore. Down the road we'll likely just count on the other wallets in the ecosystem. Actually, in some versions we have already removed hippo wallets from the frontend.
